### ISSUE TITLE
Add timeout/retry handling

### ISSUE THREAD

**Issue by haikuginger** [haikuginger/beekeeper#50]
We need to

1. Determine a good default timeout interval
2. Determine appropriate default behavior on timeout
3. Add logic to handle hive-defined timeout intervals and behavior

**Comment by haikuginger** [comment]
Let's do a default timeout interval of 5 seconds. The appropriate behavior is to not retry, but to raise an exception with a method hooked to it that will retry the request.

**Comment by haikuginger** [comment]
This is done; timeout will default to 5 seconds, or can be set differently on a per-action basis.

**Comment by virtadpt** [comment]
How can it be set differently?  Can the connection timeout be set one layer above (i.e., from a dependent module like kodipydent)?
